### 멤버조회
GET localhost:8080/me


### 멤버조회
GET localhost:8080/me
Accept: application/xml


### 멤버조회
GET localhost:8080/members

### 멤버조회
GET localhost:8080/members/shin


### 조회
GET localhost:8080/members/mandoo


###
POST localhost:8080/members
Content-Type: application/json

{
  "id" : "mandoo",
  "name" : "신건영",
  "age" : 30,
  "class" : "A",
  "role" : "member",
  "password": "mandoo"
}